# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GooglePlaces' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GooglePlaces

  	# Network
    pod 'Alamofire', '~> 4.5'
    pod 'Moya', '~> 8.0'

    # Utils
    pod 'Curry'
    pod 'Argo', '~> 4.0'

    pod 'RealmSwift'

end
